# Use prepared base image
FROM wso2cep-3.1.0
# based on centos

# Maintainer
MAINTAINER Ronald Rink <ronald.rink@d-fens.net>

RUN ln -s /opt/jre1.7.0 /opt/java
ENV JAVA_HOME /opt/java
ENV PATH ${PATH}:${JAVA_HOME}/bin

# Set environment variables
# HOME is already set correctly in centos image
# ENV HOME /root

WORKDIR /root

CMD /opt/wso2cep-3.1.0/bin/wso2server.sh
